import type { AnyHandler } from "@aotter/mantle/runtime";
import { cloudflareTurnstileCheck } from "@aotter/mantle/cloudflare";
import { buildFeatureHandlers } from "../.mantle/generated.handlers.js";
import { slackNotify } from "./slackNotify.js";

export interface HandlerEnv {
  readonly TURNSTILE_SECRET_KEY?: string;
}

/**
 * Construct the handler registry the runtime resolves
 * `Procedure.handler.ref` against. Feature handlers are generated by
 * create-mantle from the selected feature overlay set.
 */
export function buildHandlers(env: HandlerEnv): Readonly<Record<string, AnyHandler>> {
  return {
    captchaCheck: cloudflareTurnstileCheck({
      secret: env.TURNSTILE_SECRET_KEY ?? "dev-stub",
    }) as AnyHandler,
    slackNotify: slackNotify as AnyHandler,
    ...buildFeatureHandlers(env),
  };
}
