export const homeClientJs = [
  "import { collapsible } from '/enhance/collapsible.js';",
  "import { accordion } from '/enhance/accordion.js';",
  "collapsible();",
  "accordion();",
  "const THEME_KEY = 'mantle-theme';",
  "const readTheme = () => {",
  "  const stored = localStorage.getItem(THEME_KEY);",
  "  if (stored === 'light' || stored === 'dark') return stored;",
  "  return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';",
  "};",
  "const applyTheme = (theme) => {",
  "  document.documentElement.classList.toggle('dark', theme === 'dark');",
  "  document.querySelectorAll('img[src*=\"/assets/mantle-ocean-hero-light.svg\"], img[src*=\"/assets/mantle-ocean-hero-dark.svg\"]').forEach((image) => {",
  "    const src = image.getAttribute('src') || '';",
  "    const nextSrc = theme === 'dark' ? src.replace('/assets/mantle-ocean-hero-light.svg', '/assets/mantle-ocean-hero-dark.svg') : src.replace('/assets/mantle-ocean-hero-dark.svg', '/assets/mantle-ocean-hero-light.svg');",
  "    if (nextSrc && image.getAttribute('src') !== nextSrc) image.setAttribute('src', nextSrc);",
  "  });",
  "  document.querySelectorAll('[data-theme-toggle]').forEach((button) => {",
  "    button.dataset.theme = theme;",
  "    button.setAttribute('aria-pressed', theme === 'dark' ? 'true' : 'false');",
  "    button.querySelectorAll('[data-theme-label]').forEach((label) => {",
  "      label.textContent = theme === 'dark' ? 'Light mode' : 'Dark mode';",
  "    });",
  "  });",
  "};",
  "applyTheme(readTheme());",
  "window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', () => {",
  "  if (!localStorage.getItem(THEME_KEY)) applyTheme(readTheme());",
  "});",
  "document.querySelectorAll('[data-theme-toggle]').forEach((button) => {",
  "  button.addEventListener('click', () => {",
  "    const next = document.documentElement.classList.contains('dark') ? 'light' : 'dark';",
  "    localStorage.setItem(THEME_KEY, next);",
  "    applyTheme(next);",
  "  });",
  "});",
  "const updateSiteNav = () => {",
  "  document.querySelectorAll('[data-site-nav]').forEach((nav) => {",
  "    nav.dataset.scrolled = window.scrollY > 8 ? 'true' : 'false';",
  "  });",
  "};",
  "updateSiteNav();",
  "window.addEventListener('scroll', updateSiteNav, { passive: true });",
  "document.querySelectorAll('[data-mobile-nav]').forEach((sheet) => {",
  "  const root = sheet.closest('nav');",
  "  const trigger = root?.querySelector('[data-mobile-nav-trigger]');",
  "  const panel = sheet.querySelector('[data-sheet-content]');",
  "  if (!trigger) return;",
  "  const setOpen = (open) => {",
  "    sheet.dataset.state = open ? 'open' : 'closed';",
  "    trigger.setAttribute('aria-expanded', open ? 'true' : 'false');",
  "    document.body.style.overflow = open ? 'hidden' : '';",
  "    if (open) panel?.querySelector('a, button')?.focus();",
  "  };",
  "  trigger.addEventListener('click', () => setOpen(sheet.dataset.state !== 'open'));",
  "  sheet.querySelectorAll('[data-mobile-nav-close]').forEach((el) => {",
  "    el.addEventListener('click', () => setOpen(false));",
  "  });",
  "  document.addEventListener('keydown', (event) => {",
  "    if (event.key === 'Escape' && sheet.dataset.state === 'open') setOpen(false);",
  "  });",
  "});",
  "document.querySelectorAll('[data-intake-root]').forEach((root) => {",
  "  const form = root.querySelector('[data-intake-form]');",
  "  if (!form) return;",
  "  const steps = Array.from(root.querySelectorAll('[data-intake-step-panel]'));",
  "  const prev = root.querySelector('[data-intake-prev]');",
  "  const next = root.querySelector('[data-intake-next]');",
  "  const submit = root.querySelector('[data-intake-submit]');",
  "  const progress = root.querySelector('[data-intake-progress]');",
  "  const resultInput = root.querySelector('[data-intake-result-key]');",
  "  const results = Array.from(root.querySelectorAll('[data-intake-result]'));",
  "  const resultsWrap = root.querySelector('[data-intake-results]');",
  "  let current = 0;",
  "  const fieldValue = (name) => {",
  "    const value = new FormData(form).get(name);",
  "    return value == null ? '' : String(value);",
  "  };",
  "  const matches = (el) => {",
  "    const field = el.dataset.intakeWhenField || '';",
  "    if (!field) return true;",
  "    const values = (el.dataset.intakeWhenValue || '').split('|').filter(Boolean);",
  "    return values.includes(fieldValue(field));",
  "  };",
  "  const sync = () => {",
  "    root.querySelectorAll('[data-intake-field]').forEach((field) => {",
  "      const visible = matches(field);",
  "      field.hidden = !visible;",
  "      field.querySelectorAll('input, select, textarea').forEach((control) => {",
  "        control.disabled = !visible;",
  "        if (!visible) {",
  "          if (control.type === 'checkbox' || control.type === 'radio') control.checked = false;",
  "          else control.value = '';",
  "        }",
  "      });",
  "    });",
  "    current = Math.max(0, Math.min(current, steps.length - 1));",
  "    steps.forEach((step, index) => { step.hidden = index !== current; });",
  "    const selectedResult = results.find(matches) || results[0];",
  "    if (resultInput && selectedResult) resultInput.value = selectedResult.dataset.intakeResult || '';",
  "    if (progress) progress.textContent = `Step ${current + 1} of ${steps.length}`;",
  "    if (prev) prev.hidden = current === 0;",
  "    if (next) next.hidden = current >= steps.length - 1;",
  "    if (submit) submit.hidden = current < steps.length - 1;",
  "  };",
  "  form.addEventListener('input', sync);",
  "  form.addEventListener('change', sync);",
  "  prev?.addEventListener('click', () => { current -= 1; sync(); });",
  "  next?.addEventListener('click', () => { current += 1; sync(); });",
  "  form.addEventListener('mantle:form-success', () => {",
  "    const selected = resultInput?.value || '';",
  "    if (resultsWrap) resultsWrap.hidden = false;",
  "    results.forEach((result) => {",
  "      result.hidden = result.dataset.intakeResult !== selected;",
  "    });",
  "  });",
  "  sync();",
  "});",
  "document.querySelectorAll('[data-mantle-form]').forEach((form) => {",
  "  form.addEventListener('submit', async (event) => {",
  "    event.preventDefault();",
  "    const isIntake = form.dataset.intakeForm === 'true';",
  "    const status = form.querySelector('[data-mantle-form-status]');",
  "    const button = form.querySelector('button[type=\"submit\"]');",
  "    const turnstile = form.querySelector('.cf-turnstile');",
  "    const setStatus = (message, error) => {",
  "      if (!status) return;",
  "      status.hidden = false;",
  "      status.textContent = message;",
  "      if (error) status.dataset.error = 'true';",
  "      else delete status.dataset.error;",
  "    };",
  "    if (button) button.disabled = true;",
  "    setStatus(isIntake ? 'Submitting response...' : 'Sending message...', false);",
  "    try {",
  "      const body = Object.fromEntries(new FormData(form).entries());",
  "      const res = await fetch(form.action, {",
  "        method: form.method || 'POST',",
  "        headers: { 'content-type': 'application/json' },",
  "        body: JSON.stringify(body),",
  "      });",
  "      const payload = await res.json().catch(() => null);",
  "      if (!res.ok || payload?.ok === false) {",
  "        throw new Error(payload?.diagnostic?.message || 'Message could not be sent.');",
  "      }",
  "      form.dispatchEvent(new CustomEvent('mantle:form-success', { detail: { payload } }));",
  "      if (!isIntake) form.reset();",
  "      setStatus(isIntake ? 'Response saved. The site owner can review it in Mantle.' : 'Message saved. The site owner can review it in Mantle.', false);",
  "    } catch (error) {",
  "      setStatus(error instanceof Error ? error.message : 'Message could not be sent.', true);",
  "    } finally {",
  "      if (turnstile && window.turnstile?.reset) window.turnstile.reset(turnstile);",
  "      if (button) button.disabled = false;",
  "    }",
  "  });",
  "});",
  "",
].join("\n");
